In [1]:
import numpy as np
N = int(input())
#s = [list(map(int, input().split())) for l in range(N)]
s = [[3, 9, 6, 4, 6],[6, 9, 3, 1, 1],[8, 8, 9, 3, 7]]
s = np.array(s)
print(s)

# 求める最大値を二分探索
data = [i+1 for i in range(1000000000)]
left = 0 # 左のindex
right = len(data)-1 # →右のindex
x = 500 # 求めたい最大値

while left <= right:
    mid = (left + rigth) // 2
    if data[mid] == x:
        break
    elif data[mid] < value:
        left = mid + 1
    else:
        right = mid - 1

3
[[3 9 6 4 6]
 [6 9 3 1 1]
 [8 8 9 3 7]]


In [ ]:
N = int(input())
A = [tuple(map(int, input().split())) for i in range(N)]

def check(x):
    s = set()
    for a in A:
        s.add(sum(1 << i for i in range(5) if a[i] >= x))
    for x in s:
        for y in s:
            for z in s:
                if x | y | z == 31:
                    return True
    return False

ok = 0
ng = 10**9 +1
while ng - ok > 1:
    cen = (ok + ng) // 2
    if check(cen):
        ok = cen
    else:
        ng = cen
print(ok)